In [4]:
import numpy as np
import pandas as pd
from scipy.special import expit
from imblearn.over_sampling import SMOTE

In [136]:
# I relied on this book: Tariq Rashid, Create Neural Network
# Derivative on 116 page
# https://github.com/makeyourownneuralnetwork/makeyourownneuralnetwork/blob/master/part2_neural_network.ipynb

In [5]:
data=pd.read_csv('Roonyx/winequality-red.csv')

In [6]:
data.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  
0      9.4        5  
1      9.8        5

In [10]:
X=data.iloc[:,0:11].values
Y=data.loc[:,'quality'].values 

(1599, 11)

In [8]:
sm=SMOTE(random_state=3)

In [11]:
X, Y = sm.fit_sample(X, Y)

(4086, 11)

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42)

In [13]:
Y_train=Y_train-3 
Y_test=Y_test-3
#it means: 
#0 output node->quality 3
#1 node->quality 4 e.t.c

In [14]:
for i in range(11):
    X_test[:,i]/=np.max(X_test[:,i])
    X_test[:,i]+=0.01
X_test #normalize for sigmoid [0.01,1.0]

array([[0.82935484, 0.38341772, 0.51211338, ..., 0.77923077, 0.41217639,
        0.67428571],
       [0.50032258, 0.35177215, 0.15505498, ..., 0.87923077, 0.360468  ,
        0.68142857],
       [0.71039109, 0.26038366, 0.53442953, ..., 0.84759267, 0.45621635,
        0.8489415 ],
       ...,
       [0.46275443, 0.54882084, 0.05890253, ..., 0.88970894, 0.32176383,
        0.73489704],
       [0.43694142, 0.38804568, 0.01072895, ..., 0.93317983, 0.36471202,
        0.8290954 ],
       [0.48741935, 0.34544304, 0.30010995, ..., 0.81769231, 0.33748649,
        0.68142857]])

In [15]:
for i in range(11):
    X_train[:,i]/=np.max(X_train[:,i])
    X_train[:,i]+=0.01
X_train #normalize for sigmoid [0.01,1.0]

array([[0.4856124 , 0.98171562, 0.01377629, ..., 0.88093452, 0.21453155,
        0.73799543],
       [0.4372072 , 0.30834879, 0.16407562, ..., 0.85803441, 0.26240808,
        0.7510726 ],
       [0.52617619, 0.38969862, 0.24247952, ..., 0.80265829, 0.54564036,
        0.62463081],
       ...,
       [0.46283019, 0.40460421, 0.07      , ..., 0.88531172, 0.28      ,
        0.64758389],
       [0.6120111 , 0.2814778 , 0.46345555, ..., 0.80055942, 0.34910029,
        0.80503474],
       [0.66425622, 0.24444192, 0.50314811, ..., 0.78388834, 0.42383748,
        0.71635516]])

In [18]:
# X_train,X_test,Y_train,Y_test

In [19]:
framex=pd.DataFrame(X_train) #new train set
framex['quality']=Y_train
framex.head(4)

0         1         2         3         4         5         6  \
0  0.485612  0.981716  0.013776  0.163025  0.227424  0.077347  0.042449   
1  0.437207  0.308349  0.164076  0.133935  0.157603  0.065556  0.035460   
2  0.526176  0.389699  0.242480  0.115006  0.139604  0.376945  0.407716   
3  0.514063  0.637239  0.037135  0.264645  0.146701  0.083424  0.050531   

          7         8         9        10  quality  
0  1.001353  0.880935  0.214532  0.737995        0  
1  1.000728  0.858034  0.262408  0.751073        1  
2  1.003534  0.802658  0.545640  0.624631        1  
3  1.005048  0.873086  0.258567  0.735486        0

In [20]:
framex=framex.sample(frac=1)#mix it

In [21]:
framex.head(4)

0         1         2         3         4         5         6  \
3135  0.664664  0.398094  0.501298  0.145533  0.335758  0.079975  0.066182   
1209  0.790114  0.209931  0.710381  0.154600  0.127502  0.091899  0.105701   
840   0.754166  0.217589  0.653224  0.162363  0.126517  0.087721  0.092169   
3201  0.501207  0.475070  0.173979  0.142982  0.148581  0.235059  0.275518   

             7         8         9        10  quality  
3135  1.005736  0.798201  0.324771  0.574066        0  
1209  1.004874  0.735157  0.411223  0.676034        5  
840   1.004424  0.755412  0.385653  0.700262        5  
3201  1.003078  0.831798  0.295459  0.642585        1

In [22]:
framex=framex.reset_index(drop=True)#return indexes
framex.head(2)

0         1         2         3         4         5         6  \
0  0.664664  0.398094  0.501298  0.145533  0.335758  0.079975  0.066182   
1  0.790114  0.209931  0.710381  0.154600  0.127502  0.091899  0.105701   

          7         8         9        10  quality  
0  1.005736  0.798201  0.324771  0.574066        0  
1  1.004874  0.735157  0.411223  0.676034        5

In [23]:
X_new=framex.iloc[:,0:11].values
Y_new=framex.loc[:,'quality'].values #final train sets

In [25]:
#X_new,Y_new

(3268,)

In [26]:
class NeuralNetwork:
    
    def __init__(self,input_nodes,hidden_nodes,output_nodes,learning_rate):
        self.input=input_nodes
        self.hidden=hidden_nodes
        self.output=output_nodes
        self.lr=learning_rate
        self.wih=np.random.normal(0.0,self.input**-0.5,(self.hidden,self.input)) #w_input_hidden1 
        
        
        self.whh=np.random.normal(0.0,self.hidden**-0.5,(self.hidden,self.hidden)) #w_hidden1_hidden2
        
        self.who=np.random.normal(0.0,self.hidden**-0.5,(self.output,self.hidden)) #w_hidden2_output
       
    
        pass
        
    
    def train(self,X,Y):
        x=np.reshape(X,(11,1)) #1 object, 11 features
        y=np.reshape(Y,(6,1)) # 6 nodes for 6 classes
        hidden_inputs=np.dot(self.wih,x) # w_input_hidden1 * inputs
        hidden_outputs=expit(hidden_inputs) #sigmoid
        
        hidden_inputs2=np.dot(self.whh,hidden_outputs) #w_hidden1_hidden2 * hidden1_out
        hidden_outputs2=expit(hidden_inputs2)
        
        final_inputs=np.dot(self.who,hidden_outputs2)#w_hidden2_output * hidden2_out
        final_outputs=expit(final_inputs)
        
        output_errors=y-final_outputs #errors [6,1]
        print(output_errors)
        
        hidden_errors2=np.dot(self.who.T,output_errors)# errors in hiiden2 nodes
        
        self.who+=2*self.lr*np.dot((output_errors*final_outputs * (1.0-final_outputs)),hidden_outputs2.T)
        #it`s derivative: 2*(error)*Ok(1-Ok)*Oj.T and lr -> learning rate
        
        self.whh+=2*self.lr*np.dot((hidden_errors2 * hidden_outputs2 * (1.0-hidden_outputs2)),hidden_outputs.T)
        
        hidden_errors=np.dot(self.whh.T,hidden_errors2)# errors in hidden1 nodes
        
        self.wih+=2*self.lr*np.dot((hidden_errors2 * hidden_outputs * (1.0-hidden_outputs)),x.T)
        
        pass
    
    
    def predict(self,X):
        x=np.reshape(X,(11,1))
        hidden_inputs=np.dot(self.wih,x)
        hidden_outputs=expit(hidden_inputs)
        
        hidden_inputs2=np.dot(self.whh,hidden_outputs)
        hidden_outputs2=expit(hidden_inputs2)
        
        final_inputs=np.dot(self.who,hidden_outputs2)
        final_outputs=expit(final_inputs)    
        return final_outputs
    
            
    
        
    

In [27]:
D50=NeuralNetwork(11,4,6,0.1)#11 input nodes, 3 hidden nodes in each one(6), 6 output nodes

In [29]:
#train
for e in range(5):#epochs
    i=0
    for one_object in X_new:#for every object 
        targets=np.zeros(6)+0.01 #target value of this object
        targets[Y_new[i]]=0.99 #for example target is 3 -> [0.99, 0.01, 0.01, 0.01, 0.01, 0.01]
        D50.train(one_object,targets)
        i+=1 #new target for new object

[[ 0.40309206]
 [-0.57782904]
 [-0.47820697]
 [-0.61406704]
 [-0.34334847]
 [-0.39737922]]
[[-0.58506491]
 [-0.57029185]
 [-0.47235555]
 [-0.60789339]
 [-0.34045306]
 [ 0.58668562]]
[[-0.58019341]
 [-0.56351827]
 [-0.46813185]
 [-0.60146898]
 [-0.33801328]
 [ 0.57722173]]
[[-0.5716075 ]
 [ 0.4218376 ]
 [-0.46607156]
 [-0.59413032]
 [-0.33556844]
 [-0.41428694]]
[[-0.5681301 ]
 [ 0.41940679]
 [-0.4608878 ]
 [-0.58847049]
 [-0.33447892]
 [-0.40912515]]
[[ 0.41961885]
 [-0.56422391]
 [-0.45835446]
 [-0.58162589]
 [-0.3331192 ]
 [-0.40744975]]
[[-0.56461549]
 [-0.55994944]
 [-0.45410166]
 [ 0.40275653]
 [-0.32936221]
 [-0.40325483]]
[[ 0.41902341]
 [-0.55389051]
 [-0.44939791]
 [-0.57995204]
 [-0.32821449]
 [-0.39881647]]
[[-0.56649745]
 [-0.54910036]
 [-0.44464436]
 [ 0.40450009]
 [-0.32400232]
 [-0.39424424]]
[[-0.56283504]
 [-0.54450634]
 [-0.43884042]
 [-0.58065202]
 [-0.32158993]
 [ 0.59338777]]
[[-0.55730221]
 [ 0.44223198]
 [-0.43715001]
 [-0.5724324 ]
 [-0.31990523]
 [-0.39878712]]

In [30]:
#predictions on the train set
i=0
score=[]
for test in X_new:
    targets=np.zeros(6)+0.01
    targets[Y_new[i]]=0.99
    correct_answer=Y_new[i]+3
    print("True answer:",correct_answer)
    pred=D50.predict(test)
    label =np.argmax(pred)+3
    print('Pred:',label)
    if (label==correct_answer): #if prediction is true append 1, else eappend 0
        score.append(1)
    else:
        score.append(0)
    i+=1
score=np.array(score)   
print('Accuracy=',score.sum()/score.size)
    

True answer: 3
Pred: 3
True answer: 8
Pred: 8
True answer: 8
Pred: 8
True answer: 4
Pred: 4
True answer: 4
Pred: 3
True answer: 3
Pred: 3
True answer: 6
Pred: 6
True answer: 3
Pred: 3
True answer: 6
Pred: 4
True answer: 8
Pred: 8
True answer: 4
Pred: 4
True answer: 5
Pred: 4
True answer: 7
Pred: 7
True answer: 7
Pred: 8
True answer: 3
Pred: 3
True answer: 8
Pred: 8
True answer: 3
Pred: 3
True answer: 3
Pred: 3
True answer: 8
Pred: 8
True answer: 6
Pred: 5
True answer: 7
Pred: 8
True answer: 5
Pred: 4
True answer: 8
Pred: 8
True answer: 5
Pred: 8
True answer: 6
Pred: 5
True answer: 6
Pred: 6
True answer: 7
Pred: 6
True answer: 4
Pred: 4
True answer: 3
Pred: 3
True answer: 3
Pred: 3
True answer: 7
Pred: 3
True answer: 8
Pred: 8
True answer: 4
Pred: 4
True answer: 6
Pred: 4
True answer: 4
Pred: 3
True answer: 7
Pred: 8
True answer: 5
Pred: 3
True answer: 3
Pred: 3
True answer: 7
Pred: 8
True answer: 7
Pred: 8
True answer: 7
Pred: 6
True answer: 8
Pred: 8
True answer: 6
Pred: 4
True answer

In [31]:
#predictions on the test set
i=0
score=[]
for test in X_test:
    targets=np.zeros(6)+0.01
    targets[Y_new[i]]=0.99
    correct_answer=Y_test[i]+3
    print("True answer:",correct_answer)
    pred=D50.predict(test)
    label =np.argmax(pred)+3
    print('Pred:',label)
    if (label==correct_answer): #if prediction is true append 1, else eappend 0
        score.append(1)
    else:
        score.append(0)
    i+=1
score=np.array(score)   
print('Accuracy=',score.sum()/score.size)

True answer: 6
Pred: 4
True answer: 5
Pred: 4
True answer: 7
Pred: 8
True answer: 7
Pred: 8
True answer: 4
Pred: 4
True answer: 4
Pred: 4
True answer: 5
Pred: 5
True answer: 6
Pred: 4
True answer: 5
Pred: 4
True answer: 6
Pred: 4
True answer: 8
Pred: 8
True answer: 7
Pred: 8
True answer: 5
Pred: 4
True answer: 3
Pred: 3
True answer: 8
Pred: 8
True answer: 6
Pred: 6
True answer: 5
Pred: 6
True answer: 5
Pred: 4
True answer: 8
Pred: 8
True answer: 4
Pred: 3
True answer: 6
Pred: 6
True answer: 3
Pred: 3
True answer: 5
Pred: 4
True answer: 6
Pred: 4
True answer: 4
Pred: 4
True answer: 3
Pred: 3
True answer: 6
Pred: 8
True answer: 3
Pred: 3
True answer: 5
Pred: 4
True answer: 8
Pred: 8
True answer: 5
Pred: 4
True answer: 3
Pred: 4
True answer: 8
Pred: 8
True answer: 6
Pred: 8
True answer: 3
Pred: 3
True answer: 6
Pred: 4
True answer: 5
Pred: 5
True answer: 8
Pred: 8
True answer: 5
Pred: 3
True answer: 7
Pred: 8
True answer: 8
Pred: 8
True answer: 8
Pred: 8
True answer: 6
Pred: 5
True answer