In [0]:
import numpy as np

In [0]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_deriv(x):
    return sigmoid(x)*(1 - sigmoid(x))

In [51]:
x = np.random.sample((100, 2))
x

array([[0.49891759, 0.5268492 ],
       [0.49595782, 0.84606078],
       [0.15393913, 0.41537808],
       [0.85932054, 0.00245137],
       [0.07254269, 0.94586582],
       [0.45098446, 0.22282053],
       [0.94668668, 0.19531092],
       [0.95433778, 0.03746033],
       [0.94829768, 0.84375367],
       [0.3524757 , 0.85807676],
       [0.47546192, 0.42649412],
       [0.5698293 , 0.25222123],
       [0.29852195, 0.27072248],
       [0.72483501, 0.12557797],
       [0.86790664, 0.28457369],
       [0.15805417, 0.50885372],
       [0.08898159, 0.5746999 ],
       [0.41138469, 0.49370767],
       [0.27047568, 0.12140608],
       [0.31162613, 0.91408488],
       [0.53155775, 0.27529683],
       [0.58778284, 0.43476877],
       [0.76686009, 0.16836569],
       [0.82916905, 0.24455591],
       [0.04611799, 0.63271673],
       [0.82398816, 0.78628608],
       [0.57734373, 0.54826243],
       [0.50817994, 0.47953805],
       [0.54795505, 0.15900935],
       [0.68573484, 0.22927485],
       [0.

In [52]:
y = np.zeros((100))
y[10:100:10] = 1
print(y)
y = y.reshape(100, 1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


In [0]:
w0 = np.random.sample((2, 3)) - 1 #for input   - 2 inputs, 3 outputs
w1 = np.random.sample((3, 1)) - 1 #for layer 1 - 3 inputs, 1 outputs

In [0]:
#learning rate
n = 0.1

In [0]:
#Train
for i in range(10):

    #Feed forward
    layer0 = x
    layer1 = sigmoid(np.dot(layer0, w0))
    layer2 = sigmoid(np.dot(layer1, w1))

    #Back propagation using gradient descent
    layer2_error = np.multiply(np.log(layer2), y) + np.multiply((1 - y), np.log(1 - layer2))
    layer2_delta = layer2_error * sigmoid_deriv(layer2)
    
    layer1_error = layer2_delta.dot(w1.T)
    layer1_delta = layer1_error * sigmoid_deriv(layer1)
    
    w1 += layer1.T.dot(layer2_delta) * n
    w0 += layer0.T.dot(layer1_delta) * n
    i += 1

    #print(layer2_error)
    
    
    #logprobs = np.multiply(np.log(layer2), y) + np.multiply((1 - y), np.log(1 - layer2))
    #error = - np.sum(logprobs)

In [47]:
test_X = np.random.sample((10, 2))
print(test_X)

[[0.42177594 0.66412335]
 [0.69652163 0.26345042]
 [0.42976925 0.81029632]
 [0.30731262 0.3741599 ]
 [0.58065498 0.41834652]
 [0.20015283 0.09483797]
 [0.85977726 0.32049952]
 [0.36437853 0.38693172]
 [0.71455055 0.0591966 ]
 [0.11296536 0.57870186]]


In [48]:
test_Y = np.zeros((10))
test_Y[0:10:5] = 1
print(test_Y)
test_Y = test_Y.reshape(10, 1)

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [0]:
#Validate
layer0 = test_X
layer1 = sigmoid(np.dot(layer0, w0))
layer2 = sigmoid(np.dot(layer1, w1))

layer2_error = np.multiply(np.log(layer2), test_Y) + np.multiply((1 - test_Y), np.log(1 - layer2))

#logprobs = np.multiply(np.log(layer2), y) + np.multiply((1 - y), np.log(1 - layer2))
#error = - np.sum(logprobs)

In [42]:
print(layer2_error)

[[-3.50547614e-09]
 [-2.78026302e-09]
 [-2.31069619e-09]
 [-4.81819245e-08]
 [-3.63412128e-07]
 [-6.44360837e-08]
 [-3.90509925e-09]
 [-3.58347341e-09]
 [-1.52655455e-09]
 [-1.65498715e-09]
 [-2.03014520e+01]
 [-2.32045095e-09]
 [-8.17610383e-09]
 [-2.19434871e-09]
 [-2.84246849e-09]
 [-7.37486839e-08]
 [-1.74801995e-09]
 [-4.01810341e-09]
 [-4.09540330e-08]
 [-1.64503367e-09]
 [-1.74646556e+01]
 [-2.79974148e-08]
 [-2.37043030e-09]
 [-4.19295613e-08]
 [-1.52993596e-09]
 [-1.58232394e-09]
 [-1.87646077e-09]
 [-2.36300202e-07]
 [-1.49061286e-09]
 [-1.90910632e-09]
 [-1.73523242e+01]
 [-3.35379058e-09]
 [-1.76239612e-09]
 [-6.86921478e-09]
 [-1.52667745e-07]
 [-6.56433743e-09]
 [-3.09635640e-09]
 [-1.47985224e-09]
 [-5.29413204e-09]
 [-1.65278413e-09]
 [-2.02319845e+01]
 [-1.97278660e-08]
 [-4.61675979e-08]
 [-2.91589575e-09]
 [-6.79466807e-09]
 [-2.63481914e-09]
 [-1.64791247e-09]
 [-1.06411682e-06]
 [-2.02461131e-07]
 [-1.98121653e-07]
 [-1.94006312e+01]
 [-2.95265768e-09]
 [-5.5615203