In [177]:
import numpy as np

In [178]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_deriv(x):
    return sigmoid(x)*(1 - sigmoid(x))

In [231]:
x = np.array([[11, 7], [22, 14]])
x

array([[11,  7],
       [22, 14]])

In [218]:
y = np.array([[0, 1]]).T
y

array([[0],
       [1]])

In [232]:
a = sigmoid(x)
print(a)

[[0.9999833  0.99908895]
 [1.         0.99999917]]


In [219]:
w0 = 2*np.random.random((2, 3)) - 1 #for input   - 2 inputs, 3 outputs
w1 = 2*np.random.random((3, 1)) - 1 #for layer 1 - 3 inputs, 1 outputs

In [220]:
w1

array([[-0.10493844],
       [-0.11223068],
       [-0.06508704]])

In [221]:
#learning rate
n = 0.1

In [239]:
#Train
for i in range(100):

    #Feed forward
    layer0 = x
    layer1 = sigmoid(np.dot(layer0, w0))
    layer2 = sigmoid(np.dot(layer1, w1))

    #Back propagation using gradient descent
    layer2_error = y - layer2
    layer2_delta = layer2_error * sigmoid_deriv(layer2)
    
    layer1_error = layer2_delta.dot(w1.T)
    layer1_delta = layer1_error * sigmoid_deriv(layer1)
    
    w1 += layer1.T.dot(layer2_delta) * n
    w0 += layer0.T.dot(layer1_delta) * n
    i += 1
    
    logprobs = np.multiply(np.log(layer2), y) + np.multiply((1 - y), np.log(1 - layer2))
    error = - np.sum(logprobs)

C:\Users\molko\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [240]:
#Validate
layer0 = np.array([[9, 7], [4, 6]])
layer1 = sigmoid(np.dot(layer0, w0))
layer2 = sigmoid(np.dot(layer1, w1))

layer2_error = y - layer2

logprobs = np.multiply(np.log(layer2), y) + np.multiply((1 - y), np.log(1 - layer2))
error = - np.sum(logprobs)

C:\Users\molko\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
