In [0]:
import numpy as np

In [0]:
train_X = np.random.sample((100, 2))
print(train_X)
train_X.shape

[[0.71369021 0.11750406]
 [0.84639598 0.56488098]
 [0.46000194 0.43069852]
 [0.80624257 0.3310152 ]
 [0.33096063 0.47357903]
 [0.4846123  0.13685741]
 [0.03291521 0.24959589]
 [0.34700664 0.05592316]
 [0.26705011 0.17853629]
 [0.80208493 0.3572843 ]
 [0.26289047 0.03780418]
 [0.55877873 0.86017207]
 [0.83065614 0.8244651 ]
 [0.9128948  0.85039725]
 [0.0203422  0.96374584]
 [0.05032388 0.92406431]
 [0.75239689 0.28100734]
 [0.51090548 0.7392636 ]
 [0.91820344 0.76728089]
 [0.2890771  0.62202004]
 [0.50265991 0.57112161]
 [0.40056638 0.09667771]
 [0.09793379 0.28826164]
 [0.09612412 0.90708612]
 [0.29462199 0.47555539]
 [0.24579036 0.72716701]
 [0.21419094 0.55235249]
 [0.51466607 0.2787798 ]
 [0.54494473 0.16936932]
 [0.2779276  0.05836004]
 [0.11896161 0.09986178]
 [0.75582699 0.6134548 ]
 [0.51813741 0.59830897]
 [0.44269883 0.18747119]
 [0.34097362 0.88793655]
 [0.26007532 0.45663888]
 [0.19554689 0.44337987]
 [0.4445793  0.53922302]
 [0.74700586 0.21560175]
 [0.57176503 0.25442831]


(100, 2)

In [0]:
train_Y = np.zeros((100))

In [0]:
train_Y[10:100:10] = 1
print(train_Y)
train_Y = train_Y.reshape(100, 1)
train_Y.shape

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]]


(100, 1)

In [0]:
test_X = np.random.sample((10, 2))
print(test_X)

[[0.66205227 0.63532349]
 [0.8960098  0.46052255]
 [0.99297525 0.67474582]
 [0.22549546 0.11475911]
 [0.61441555 0.8339905 ]
 [0.74750703 0.81750086]
 [0.34232935 0.95441812]
 [0.8367912  0.70819838]
 [0.86222918 0.61061261]
 [0.29499325 0.916305  ]]


In [0]:
test_Y = np.zeros((10))
test_Y[0:10:5] = 1
print(test_Y)
test_Y = test_Y.reshape(10, 1)

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [0]:
import keras
from keras import models
from keras import layers

In [0]:
test_X.shape

(10, 2)

In [0]:
test_Y.shape

(10, 1)

In [0]:
model = keras.Sequential([
    keras.layers.Dense(3, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

In [0]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [0]:
model.fit(train_X, train_Y, epochs=100, batch_size=32)

Epoch 1/100
100/100 [==============================] - 0s 3ms/step - loss: 0.7466 - accuracy: 0.2700
Epoch 2/100
100/100 [==============================] - 0s 92us/step - loss: 0.7386 - accuracy: 0.2800
Epoch 3/100
100/100 [==============================] - 0s 88us/step - loss: 0.7331 - accuracy: 0.3200
Epoch 4/100
100/100 [==============================] - 0s 88us/step - loss: 0.7284 - accuracy: 0.3100
Epoch 5/100
100/100 [==============================] - 0s 81us/step - loss: 0.7241 - accuracy: 0.3400
Epoch 6/100
100/100 [==============================] - 0s 83us/step - loss: 0.7201 - accuracy: 0.3400
Epoch 7/100
100/100 [==============================] - 0s 69us/step - loss: 0.7162 - accuracy: 0.3400
Epoch 8/100
100/100 [==============================] - 0s 80us/step - loss: 0.7125 - accuracy: 0.3500
Epoch 9/100
100/100 [==============================] - 0s 81us/step - loss: 0.7091 - accuracy: 0.3700
Epoch 10/100
100/100 [==============================] - 0s 82us/step - loss: 0.7055

In [0]:
test_loss, test_acc = model.evaluate(test_X, test_Y)

10/10 [==============================] - 0s 327us/step


In [0]:
print('test_acc:', test_acc)

test_acc: 0.800000011920929
